define(['backbone'], function(Backbone) {

  return new Backbone.Collection([
    {
      "cc":"ABW",
      "en":"Aruba",
      "nl":"Aruba"
    },
    {
      "cc":"AFG",
      "en":"Afghanistan",
      "nl":"Afghanistan"
    },
    {
      "cc":"AGO",
      "en":"Angola",
      "nl":"Angola"
    },
    {
      "cc":"AIA",
      "en":"Anguilla",
      "nl":"Anguilla"
    },
    {
      "cc":"ALA",
      "en":"Åland Islands",
      "nl":"Åland"
    },
    {
      "cc":"ALB",
      "en":"Albania",
      "nl":"Albanië"
    },
    {
      "cc":"AND",
      "en":"Andorra",
      "nl":"Andorra"
    },
    {
      "cc":"ARE",
      "en":"United Arab Emirates",
      "nl":"Verenigde Arabische Emiraten"
    },
    {
      "cc":"ARG",
      "en":"Argentina",
      "nl":"Argentinië"
    },
    {
      "cc":"ARM",
      "en":"Armenia",
      "nl":"Armenië"
    },
    {
      "cc":"ASM",
      "en":"American Samoa",
      "nl":"Amerikaans-Samoa"
    },
    {
      "cc":"ATA",
      "en":"Antarctica",
      "nl":"Antarctica"
    },
    {
      "cc":"ATF",
      "en":"French Southern Territories",
      "nl":"Franse Zuidelijke en Antarctische Gebieden"
    },
    {
      "cc":"ATG",
      "en":"Antigua and Barbuda",
      "nl":"Antigua en Barbuda"
    },
    {
      "cc":"AUS",
      "en":"Australia",
      "nl":"Australië"
    },
    {
      "cc":"AUT",
      "en":"Austria",
      "nl":"Oostenrijk"
    },
    {
      "cc":"AZE",
      "en":"Azerbaijan",
      "nl":"Azerbeidzjan"
    },
    {
      "cc":"BDI",
      "en":"Burundi",
      "nl":"Burundi"
    },
    {
      "cc":"BEL",
      "en":"Belgium",
      "nl":"België"
    },
    {
      "cc":"BEN",
      "en":"Benin",
      "nl":"Benin"
    },
    {
      "cc":"BES",
      "en":"Bonaire, Sint Eustatius and Saba",
      "nl":"Bonaire, Sint Eustatius en Saba"
    },
    {
      "cc":"BFA",
      "en":"Burkina Faso",
      "nl":"Burkina Faso"
    },
    {
      "cc":"BGD",
      "en":"Bangladesh",
      "nl":"Bangladesh"
    },
    {
      "cc":"BGR",
      "en":"Bulgaria",
      "nl":"Bulgarije"
    },
    {
      "cc":"BHR",
      "en":"Bahrain",
      "nl":"Bahrein"
    },
    {
      "cc":"BHS",
      "en":"Bahamas",
      "nl":"Bahama's"
    },
    {
      "cc":"BIH",
      "en":"Bosnia and Herzegovina",
      "nl":"Bosnië en Herzegovina"
    },
    {
      "cc":"BLM",
      "en":"Saint Barthélemy",
      "nl":"Saint-Barthélemy"
    },
    {
      "cc":"BLR",
      "en":"Belarus",
      "nl":"Wit-Rusland"
    },
    {
      "cc":"BLZ",
      "en":"Belize",
      "nl":"Belize"
    },
    {
      "cc":"BMU",
      "en":"Bermuda",
      "nl":"Bermuda"
    },
    {
      "cc":"BOL",
      "en":"Bolivia, Plurinational State of",
      "nl":"Bolivia"
    },
    {
      "cc":"BRA",
      "en":"Brazil",
      "nl":"Brazilië"
    },
    {
      "cc":"BRB",
      "en":"Barbados",
      "nl":"Barbados"
    },
    {
      "cc":"BRN",
      "en":"Brunei Darussalam",
      "nl":"Brunei"
    },
    {
      "cc":"BTN",
      "en":"Bhutan",
      "nl":"Bhutan"
    },
    {
      "cc":"BVT",
      "en":"Bouvet Island",
      "nl":"Bouveteiland"
    },
    {
      "cc":"BWA",
      "en":"Botswana",
      "nl":"Botswana"
    },
    {
      "cc":"CAF",
      "en":"Central African Republic",
      "nl":"Centraal-Afrikaanse Republiek"
    },
    {
      "cc":"CAN",
      "en":"Canada",
      "nl":"Canada"
    },
    {
      "cc":"CCK",
      "en":"Cocos (Keeling) Islands",
      "nl":"Cocoseilanden"
    },
    {
      "cc":"CHE",
      "en":"Switzerland",
      "nl":"Zwitserland"
    },
    {
      "cc":"CHL",
      "en":"Chile",
      "nl":"Chili"
    },
    {
      "cc":"CHN",
      "en":"China",
      "nl":"China"
    },
    {
      "cc":"CIV",
      "en":"Côte d'Ivoire",
      "nl":"Ivoorkust"
    },
    {
      "cc":"CMR",
      "en":"Cameroon",
      "nl":"Kameroen"
    },
    {
      "cc":"COD",
      "en":"Congo, the Democratic Republic of the",
      "nl":"Congo-Kinshasa"
    },
    {
      "cc":"COG",
      "en":"Congo",
      "nl":"Congo-Brazzaville"
    },
    {
      "cc":"COK",
      "en":"Cook Islands",
      "nl":"Cookeilanden"
    },
    {
      "cc":"COL",
      "en":"Colombia",
      "nl":"Colombia"
    },
    {
      "cc":"COM",
      "en":"Comoros",
      "nl":"Comoren"
    },
    {
      "cc":"CPV",
      "en":"Cape Verde",
      "nl":"Kaapverdië"
    },
    {
      "cc":"CRI",
      "en":"Costa Rica",
      "nl":"Costa Rica"
    },
    {
      "cc":"CUB",
      "en":"Cuba",
      "nl":"Cuba"
    },
    {
      "cc":"CUW",
      "en":"Curaçao",
      "nl":"Curaçao"
    },
    {
      "cc":"CXR",
      "en":"Christmas Island",
      "nl":"Christmaseiland"
    },
    {
      "cc":"CYM",
      "en":"Cayman Islands",
      "nl":"Kaaimaneilanden"
    },
    {
      "cc":"CYP",
      "en":"Cyprus",
      "nl":"Cyprus"
    },
    {
      "cc":"CZE",
      "en":"Czech Republic",
      "nl":"Tsjechië"
    },
    {
      "cc":"DEU",
      "en":"Germany",
      "nl":"Duitsland"
    },
    {
      "cc":"DJI",
      "en":"Djibouti",
      "nl":"Djibouti"
    },
    {
      "cc":"DMA",
      "en":"Dominica",
      "nl":"Dominica"
    },
    {
      "cc":"DNK",
      "en":"Denmark",
      "nl":"Denemarken"
    },
    {
      "cc":"DOM",
      "en":"Dominican Republic",
      "nl":"Dominicaanse Republiek"
    },
    {
      "cc":"DZA",
      "en":"Algeria",
      "nl":"Algerije"
    },
    {
      "cc":"ECU",
      "en":"Ecuador",
      "nl":"Ecuador"
    },
    {
      "cc":"EGY",
      "en":"Egypt",
      "nl":"Egypte"
    },
    {
      "cc":"ERI",
      "en":"Eritrea",
      "nl":"Eritrea"
    },
    {
      "cc":"ESH",
      "en":"Western Sahara",
      "nl":"Westelijke Sahara"
    },
    {
      "cc":"ESP",
      "en":"Spain",
      "nl":"Spanje"
    },
    {
      "cc":"EST",
      "en":"Estonia",
      "nl":"Estland"
    },
    {
      "cc":"ETH",
      "en":"Ethiopia",
      "nl":"Ethiopië"
    },
    {
      "cc":"FIN",
      "en":"Finland",
      "nl":"Finland"
    },
    {
      "cc":"FJI",
      "en":"Fiji",
      "nl":"Fiji"
    },
    {
      "cc":"FLK",
      "en":"Falkland Islands (Malvinas)",
      "nl":"Falklandeilanden"
    },
    {
      "cc":"FRA",
      "en":"France",
      "nl":"Frankrijk"
    },
    {
      "cc":"FRO",
      "en":"Faroe Islands",
      "nl":"Faeröer"
    },
    {
      "cc":"FSM",
      "en":"Micronesia, Federated States of",
      "nl":"Micronesia"
    },
    {
      "cc":"GAB",
      "en":"Gabon",
      "nl":"Gabon"
    },
    {
      "cc":"GBR",
      "en":"United Kingdom",
      "nl":"Verenigd Koninkrijk"
    },
    {
      "cc":"GEO",
      "en":"Georgia",
      "nl":"Georgië"
    },
    {
      "cc":"GGY",
      "en":"Guernsey",
      "nl":"Guernsey"
    },
    {
      "cc":"GHA",
      "en":"Ghana",
      "nl":"Ghana"
    },
    {
      "cc":"GIB",
      "en":"Gibraltar",
      "nl":"Gibraltar"
    },
    {
      "cc":"GIN",
      "en":"Guinea",
      "nl":"Guinee"
    },
    {
      "cc":"GLP",
      "en":"Guadeloupe",
      "nl":"Guadeloupe"
    },
    {
      "cc":"GMB",
      "en":"Gambia",
      "nl":"Gambia"
    },
    {
      "cc":"GNB",
      "en":"Guinea-Bissau",
      "nl":"Guinee-Bissau"
    },
    {
      "cc":"GNQ",
      "en":"Equatorial Guinea",
      "nl":"Equatoriaal-Guinea"
    },
    {
      "cc":"GRC",
      "en":"Greece",
      "nl":"Griekenland"
    },
    {
      "cc":"GRD",
      "en":"Grenada",
      "nl":"Grenada"
    },
    {
      "cc":"GRL",
      "en":"Greenland",
      "nl":"Groenland"
    },
    {
      "cc":"GTM",
      "en":"Guatemala",
      "nl":"Guatemala"
    },
    {
      "cc":"GUF",
      "en":"French Guiana",
      "nl":"Frans-Guyana"
    },
    {
      "cc":"GUM",
      "en":"Guam",
      "nl":"Guam"
    },
    {
      "cc":"GUY",
      "en":"Guyana",
      "nl":"Guyana"
    },
    {
      "cc":"HKG",
      "en":"Hong Kong",
      "nl":"Hongkong"
    },
    {
      "cc":"HMD",
      "en":"Heard Island and McDonald Islands",
      "nl":"Heard en MacDonaldeilanden"
    },
    {
      "cc":"HND",
      "en":"Honduras",
      "nl":"Honduras"
    },
    {
      "cc":"HRV",
      "en":"Croatia",
      "nl":"Kroatië"
    },
    {
      "cc":"HTI",
      "en":"Haiti",
      "nl":"Haïti"
    },
    {
      "cc":"HUN",
      "en":"Hungary",
      "nl":"Hongarije"
    },
    {
      "cc":"IDN",
      "en":"Indonesia",
      "nl":"Indonesië"
    },
    {
      "cc":"IMN",
      "en":"Isle of Man",
      "nl":"Man"
    },
    {
      "cc":"IND",
      "en":"India",
      "nl":"India"
    },
    {
      "cc":"IOT",
      "en":"British Indian Ocean Territory",
      "nl":"Brits Indische Oceaanterritorium"
    },
    {
      "cc":"IRL",
      "en":"Ireland",
      "nl":"Ierland"
    },
    {
      "cc":"IRN",
      "en":"Iran, Islamic Republic of",
      "nl":"Iran"
    },
    {
      "cc":"IRQ",
      "en":"Iraq",
      "nl":"Irak"
    },
    {
      "cc":"ISL",
      "en":"Iceland",
      "nl":"IJsland"
    },
    {
      "cc":"ISR",
      "en":"Israel",
      "nl":"Israël"
    },
    {
      "cc":"ITA",
      "en":"Italy",
      "nl":"Italië"
    },
    {
      "cc":"JAM",
      "en":"Jamaica",
      "nl":"Jamaica"
    },
    {
      "cc":"JEY",
      "en":"Jersey",
      "nl":"Jersey"
    },
    {
      "cc":"JOR",
      "en":"Jordan",
      "nl":"Jordanië"
    },
    {
      "cc":"JPN",
      "en":"Japan",
      "nl":"Japan"
    },
    {
      "cc":"KAZ",
      "en":"Kazakhstan",
      "nl":"Kazachstan"
    },
    {
      "cc":"KEN",
      "en":"Kenya",
      "nl":"Kenia"
    },
    {
      "cc":"KGZ",
      "en":"Kyrgyzstan",
      "nl":"Kirgizië"
    },
    {
      "cc":"KHM",
      "en":"Cambodia",
      "nl":"Cambodja"
    },
    {
      "cc":"KIR",
      "en":"Kiribati",
      "nl":"Kiribati"
    },
    {
      "cc":"KNA",
      "en":"Saint Kitts and Nevis",
      "nl":"Saint Kitts en Nevis"
    },
    {
      "cc":"KOR",
      "en":"Korea, Republic of",
      "nl":"Zuid-Korea"
    },
    {
      "cc":"KWT",
      "en":"Kuwait",
      "nl":"Koeweit"
    },
    {
      "cc":"LAO",
      "en":"Lao People's Democratic Republic",
      "nl":"Laos"
    },
    {
      "cc":"LBN",
      "en":"Lebanon",
      "nl":"Libanon"
    },
    {
      "cc":"LBR",
      "en":"Liberia",
      "nl":"Liberia"
    },
    {
      "cc":"LBY",
      "en":"Libya",
      "nl":"Libië"
    },
    {
      "cc":"LCA",
      "en":"Saint Lucia",
      "nl":"Saint Lucia"
    },
    {
      "cc":"LIE",
      "en":"Liechtenstein",
      "nl":"Liechtenstein"
    },
    {
      "cc":"LKA",
      "en":"Sri Lanka",
      "nl":"Sri Lanka"
    },
    {
      "cc":"LSO",
      "en":"Lesotho",
      "nl":"Lesotho"
    },
    {
      "cc":"LTU",
      "en":"Lithuania",
      "nl":"Litouwen"
    },
    {
      "cc":"LUX",
      "en":"Luxembourg",
      "nl":"Luxemburg"
    },
    {
      "cc":"LVA",
      "en":"Latvia",
      "nl":"Letland"
    },
    {
      "cc":"MAC",
      "en":"Macao",
      "nl":"Macau"
    },
    {
      "cc":"MAF",
      "en":"Saint Martin (French part)",
      "nl":"Sint-Maarten"
    },
    {
      "cc":"MAR",
      "en":"Morocco",
      "nl":"Marokko"
    },
    {
      "cc":"MCO",
      "en":"Monaco",
      "nl":"Monaco"
    },
    {
      "cc":"MDA",
      "en":"Moldova, Republic of",
      "nl":"Moldavië"
    },
    {
      "cc":"MDG",
      "en":"Madagascar",
      "nl":"Madagaskar"
    },
    {
      "cc":"MDV",
      "en":"Maldives",
      "nl":"Maldiven"
    },
    {
      "cc":"MEX",
      "en":"Mexico",
      "nl":"Mexico"
    },
    {
      "cc":"MHL",
      "en":"Marshall Islands",
      "nl":"Marshalleilanden"
    },
    {
      "cc":"MKD",
      "en":"Macedonia, the former Yugoslav Republic of",
      "nl":"Macedonië"
    },
    {
      "cc":"MLI",
      "en":"Mali",
      "nl":"Mali"
    },
    {
      "cc":"MLT",
      "en":"Malta",
      "nl":"Malta"
    },
    {
      "cc":"MMR",
      "en":"Myanmar",
      "nl":"Myanmar"
    },
    {
      "cc":"MNE",
      "en":"Montenegro",
      "nl":"Montenegro"
    },
    {
      "cc":"MNG",
      "en":"Mongolia",
      "nl":"Mongolië"
    },
    {
      "cc":"MNP",
      "en":"Northern Mariana Islands",
      "nl":"Noordelijke Marianen"
    },
    {
      "cc":"MOZ",
      "en":"Mozambique",
      "nl":"Mozambique"
    },
    {
      "cc":"MRT",
      "en":"Mauritania",
      "nl":"Mauritanië"
    },
    {
      "cc":"MSR",
      "en":"Montserrat",
      "nl":"Montserrat"
    },
    {
      "cc":"MTQ",
      "en":"Martinique",
      "nl":"Martinique"
    },
    {
      "cc":"MUS",
      "en":"Mauritius",
      "nl":"Mauritius"
    },
    {
      "cc":"MWI",
      "en":"Malawi",
      "nl":"Malawi"
    },
    {
      "cc":"MYS",
      "en":"Malaysia",
      "nl":"Maleisië"
    },
    {
      "cc":"MYT",
      "en":"Mayotte",
      "nl":"Mayotte"
    },
    {
      "cc":"NAM",
      "en":"Namibia",
      "nl":"Namibië"
    },
    {
      "cc":"NCL",
      "en":"New Caledonia",
      "nl":"Nieuw-Caledonië"
    },
    {
      "cc":"NER",
      "en":"Niger",
      "nl":"Niger"
    },
    {
      "cc":"NFK",
      "en":"Norfolk Island",
      "nl":"Norfolk"
    },
    {
      "cc":"NGA",
      "en":"Nigeria",
      "nl":"Nigeria"
    },
    {
      "cc":"NIC",
      "en":"Nicaragua",
      "nl":"Nicaragua"
    },
    {
      "cc":"NIU",
      "en":"Niue",
      "nl":"Niue"
    },
    {
      "cc":"NLD",
      "en":"Netherlands",
      "nl":"Nederland"
    },
    {
      "cc":"NOR",
      "en":"Norway",
      "nl":"Noorwegen"
    },
    {
      "cc":"NPL",
      "en":"Nepal",
      "nl":"Nepal"
    },
    {
      "cc":"NRU",
      "en":"Nauru",
      "nl":"Nauru"
    },
    {
      "cc":"NZL",
      "en":"New Zealand",
      "nl":"Nieuw-Zeeland"
    },
    {
      "cc":"OMN",
      "en":"Oman",
      "nl":"Oman"
    },
    {
      "cc":"PAK",
      "en":"Pakistan",
      "nl":"Pakistan"
    },
    {
      "cc":"PAN",
      "en":"Panama",
      "nl":"Panama"
    },
    {
      "cc":"PCN",
      "en":"Pitcairn",
      "nl":"Pitcairneilanden"
    },
    {
      "cc":"PER",
      "en":"Peru",
      "nl":"Peru"
    },
    {
      "cc":"PHL",
      "en":"Philippines",
      "nl":"Filipijnen"
    },
    {
      "cc":"PLW",
      "en":"Palau",
      "nl":"Palau"
    },
    {
      "cc":"PNG",
      "en":"Papua New Guinea",
      "nl":"Papoea-Nieuw-Guinea"
    },
    {
      "cc":"POL",
      "en":"Poland",
      "nl":"Polen"
    },
    {
      "cc":"PRI",
      "en":"Puerto Rico",
      "nl":"Puerto Rico"
    },
    {
      "cc":"PRK",
      "en":"Korea, Democratic People's Republic of",
      "nl":"Noord-Korea"
    },
    {
      "cc":"PRT",
      "en":"Portugal",
      "nl":"Portugal"
    },
    {
      "cc":"PRY",
      "en":"Paraguay",
      "nl":"Paraguay"
    },
    {
      "cc":"PSE",
      "en":"Palestine, State of",
      "nl":"Palestina"
    },
    {
      "cc":"PYF",
      "en":"French Polynesia",
      "nl":"Frans-Polynesië"
    },
    {
      "cc":"QAT",
      "en":"Qatar",
      "nl":"Qatar"
    },
    {
      "cc":"REU",
      "en":"Réunion",
      "nl":"Réunion"
    },
    {
      "cc":"ROU",
      "en":"Romania",
      "nl":"Roemenië"
    },
    {
      "cc":"RUS",
      "en":"Russian Federation",
      "nl":"Rusland"
    },
    {
      "cc":"RWA",
      "en":"Rwanda",
      "nl":"Rwanda"
    },
    {
      "cc":"SAU",
      "en":"Saudi Arabia",
      "nl":"Saoedi-Arabië"
    },
    {
      "cc":"SDN",
      "en":"Sudan",
      "nl":"Soedan"
    },
    {
      "cc":"SEN",
      "en":"Senegal",
      "nl":"Senegal"
    },
    {
      "cc":"SGP",
      "en":"Singapore",
      "nl":"Singapore"
    },
    {
      "cc":"SGS",
      "en":"South Georgia and the South Sandwich Islands",
      "nl":"Zuid-Georgia en de Zuidelijke Sandwicheilanden"
    },
    {
      "cc":"SHN",
      "en":"Saint Helena, Ascension and Tristan da Cunha",
      "nl":"Sint-Helena, Ascension en Tristan da Cunha"
    },
    {
      "cc":"SJM",
      "en":"Svalbard and Jan Mayen",
      "nl":"Spitsbergen en Jan Mayen"
    },
    {
      "cc":"SLB",
      "en":"Solomon Islands",
      "nl":"Salomonseilanden"
    },
    {
      "cc":"SLE",
      "en":"Sierra Leone",
      "nl":"Sierra Leone"
    },
    {
      "cc":"SLV",
      "en":"El Salvador",
      "nl":"El Salvador"
    },
    {
      "cc":"SMR",
      "en":"San Marino",
      "nl":"San Marino"
    },
    {
      "cc":"SOM",
      "en":"Somalia",
      "nl":"Somalië"
    },
    {
      "cc":"SPM",
      "en":"Saint Pierre and Miquelon",
      "nl":"Saint-Pierre en Miquelon"
    },
    {
      "cc":"SRB",
      "en":"Serbia",
      "nl":"Servië"
    },
    {
      "cc":"SSD",
      "en":"South Sudan",
      "nl":"Zuid-Soedan"
    },
    {
      "cc":"STP",
      "en":"Sao Tome and Principe",
      "nl":"Sao Tomé en Principe"
    },
    {
      "cc":"SUR",
      "en":"Suriname",
      "nl":"Suriname"
    },
    {
      "cc":"SVK",
      "en":"Slovakia",
      "nl":"Slowakije"
    },
    {
      "cc":"SVN",
      "en":"Slovenia",
      "nl":"Slovenië"
    },
    {
      "cc":"SWE",
      "en":"Sweden",
      "nl":"Zweden"
    },
    {
      "cc":"SWZ",
      "en":"Swaziland",
      "nl":"Swaziland"
    },
    {
      "cc":"SXM",
      "en":"Sint Maarten (Dutch part)",
      "nl":"Sint Maarten"
    },
    {
      "cc":"SYC",
      "en":"Seychelles",
      "nl":"Seychellen"
    },
    {
      "cc":"SYR",
      "en":"Syrian Arab Republic",
      "nl":"Syrië"
    },
    {
      "cc":"TCA",
      "en":"Turks and Caicos Islands",
      "nl":"Turks- en Caicoseilanden"
    },
    {
      "cc":"TCD",
      "en":"Chad",
      "nl":"Tsjaad"
    },
    {
      "cc":"TGO",
      "en":"Togo",
      "nl":"Togo"
    },
    {
      "cc":"THA",
      "en":"Thailand",
      "nl":"Thailand"
    },
    {
      "cc":"TJK",
      "en":"Tajikistan",
      "nl":"Tadzjikistan"
    },
    {
      "cc":"TKL",
      "en":"Tokelau",
      "nl":"Tokelau"
    },
    {
      "cc":"TKM",
      "en":"Turkmenistan",
      "nl":"Turkmenistan"
    },
    {
      "cc":"TLS",
      "en":"Timor-Leste",
      "nl":"Oost-Timor"
    },
    {
      "cc":"TON",
      "en":"Tonga",
      "nl":"Tonga"
    },
    {
      "cc":"TTO",
      "en":"Trinidad and Tobago",
      "nl":"Trinidad en Tobago"
    },
    {
      "cc":"TUN",
      "en":"Tunisia",
      "nl":"Tunesië"
    },
    {
      "cc":"TUR",
      "en":"Turkey",
      "nl":"Turkije"
    },
    {
      "cc":"TUV",
      "en":"Tuvalu",
      "nl":"Tuvalu"
    },
    {
      "cc":"TWN",
      "en":"Taiwan, Province of China",
      "nl":"Taiwan"
    },
    {
      "cc":"TZA",
      "en":"Tanzania, United Republic of",
      "nl":"Tanzania"
    },
    {
      "cc":"UGA",
      "en":"Uganda",
      "nl":"Oeganda"
    },
    {
      "cc":"UKR",
      "en":"Ukraine",
      "nl":"Oekraïne"
    },
    {
      "cc":"UMI",
      "en":"United States Minor Outlying Islands",
      "nl":"Kleine Pacifische eilanden van de Verenigde Staten"
    },
    {
      "cc":"URY",
      "en":"Uruguay",
      "nl":"Uruguay"
    },
    {
      "cc":"USA",
      "en":"United States",
      "nl":"Verenigde Staten"
    },
    {
      "cc":"UZB",
      "en":"Uzbekistan",
      "nl":"Oezbekistan"
    },
    {
      "cc":"VAT",
      "en":"Holy See (Vatican City State)",
      "nl":"Vaticaanstad"
    },
    {
      "cc":"VCT",
      "en":"Saint Vincent and the Grenadines",
      "nl":"Saint Vincent en de Grenadines"
    },
    {
      "cc":"VEN",
      "en":"Venezuela, Bolivarian Republic of",
      "nl":"Venezuela"
    },
    {
      "cc":"VGB",
      "en":"Virgin Islands, British",
      "nl":"Britse Maagdeneilanden"
    },
    {
      "cc":"VIR",
      "en":"Virgin Islands, U.S.",
      "nl":"Amerikaanse Maagdeneilanden"
    },
    {
      "cc":"VNM",
      "en":"Viet Nam",
      "nl":"Vietnam"
    },
    {
      "cc":"VUT",
      "en":"Vanuatu",
      "nl":"Vanuatu"
    },
    {
      "cc":"WLF",
      "en":"Wallis and Futuna",
      "nl":"Wallis en Futuna"
    },
    {
      "cc":"WSM",
      "en":"Samoa",
      "nl":"Samoa"
    },
    {
      "cc":"YEM",
      "en":"Yemen",
      "nl":"Jemen"
    },
    {
      "cc":"ZAF",
      "en":"South Africa",
      "nl":"Zuid-Afrika"
    },
    {
      "cc":"ZMB",
      "en":"Zambia",
      "nl":"Zambia"
    },
    {
      "cc":"ZWE",
      "en":"Zimbabwe",
      "nl":"Zimbabwe"
    }
  ]);

});